<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="PRATIKSHA-07" failures="2" tests="3" name="Default test(failed)" time="0.055" errors="0" timestamp="2023-12-22T22:48:10 IST">
  <testcase classname="failTestCase.DEmo1" name="Test_3" time="0.01">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at failTestCase.DEmo1.Test_3(DEmo1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test_3 -->
  <testcase classname="failTestCase.DEmo1" name="Test_2" time="0.002"/>
  <testcase classname="failTestCase.DEmo1" name="Test_4" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at failTestCase.DEmo1.Test_4(DEmo1.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test_4 -->
  <testcase classname="failTestCase.DEmo1" name="Test_1" time="0.0">
    <ignored/>
  </testcase> <!-- Test_1 -->
  <testcase classname="failTestCase.DEmo1" name="Test_5" time="0.0">
    <ignored/>
  </testcase> <!-- Test_5 -->
</testsuite> <!-- Default test(failed) -->
